import time

input = input('Enter Name => ')
print(f'Hacking Facebook:{input}')
time.sleep(1.5)
print('10%')
time.sleep(1)
print('20%')
time.sleep(1)
print('30%')
time.sleep(1)
print('40%')
time.sleep(1)
print('50%')
time.sleep(1)
print('60%')
time.sleep(1)
print('70%')
time.sleep(1)
print('80%')
time.sleep(1)
print('90%')
time.sleep(1)
print('100%')
time.sleep(1)
print(f'{input} was hacked!')